add pre-checkout
add pre-checkout

add pre-checkout

add pagination

add pagination

fix pipeline

add cancelling build

update readme

update readme

fix pagination

fix pagination

fix pagination

fix pagination

fix pagination

check pre-check

add plugin helper

add plugin helper

add plugin helper

fix helper

fix path

api token name

debug

debug

add test

add test

remove test

remove header

remove header

remove header

remove header

check token

check token

remove noen

add shell check

add tests

add tests

add tests

add tests

add tests

add tests

remove tests

Fix env

Fix env

Fix env

Fix env

Fix env

fix env reading

fix env reading

remove exit 1 when token not found

remove exit 1 when token not found

remove unnecessary print

reduce logging noise

update readme

update test

update test

update test

update test

update test

removing tests for now

update readme

remove echo

cleanup

Remove exit

add tests and review comments

add tests and review comments

add tests and review comments

add tests and review comments

add tests and review comments

add tests and review comments

remove token var

diff --git a/hooks/pre-checkout b/hooks/pre-checkout
--- a/hooks/pre-checkout
+++ b/hooks/pre-checkout
@@ -1,36 +1,50 @@
 #!/bin/bash
-
 set -euo pipefail
 
+echo "🔍 Checking existing builds for commit $BUILDKITE_COMMIT..."
 
-echo "skipping an existing commit"
+url="https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds?commit=${BUILDKITE_COMMIT}"
 
-echo "🔍 Checking for existing builds for commit $BUILDKITE_COMMIT..."
+if [[ -z "${BUILDKITE_PLUGIN_SKIP_BUILD_FOR_COMMIT_READ_BUILD_TOKEN_ENV:-}" ]]; then
+  echo "❌ Missing mandatory option: commit-message-substring"
+  exit 1
+fi
 
-#Fetch builds ran on this commit
+token_var="${BUILDKITE_PLUGIN_SKIP_BUILD_FOR_COMMIT_READ_BUILD_TOKEN_ENV:-}"
 
-response=$(curl -s -H "Authorization: Bearer ${buildkite_api_token}" \
-  "https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds?commit=${BUILDKITE_COMMIT}")
+# Reading header and body into temporary files
+headers=$(mktemp)
+body=$(mktemp)
 
+# Calling the API
+curl -sS -o "$body" -D "$headers" -H "Authorization: Bearer ${!token_var}" "$url"
 
-echo "Response ${response}"
+# Checking HTTP status
+status=$(head -n 1 "$headers" | awk '{print $2}')
+if [[ "$status" == "404" ]]; then
+  echo "🚨 404 Not Found: The requested resource could not be found."
+  rm -f "$headers" "$body"
+fi
 
+# Parse build numbers from body
+build_numbers=$(grep -o '"number":[0-9]\+' "$body" | grep -o '[0-9]\+' | sed 's/^0*//')
+duplicate_found=false
 
-# Extract build numbers from the response
-build_numbers=$(echo "$response" | grep -o '"number":[0-9]\+' | grep -o '[0-9]\+')
-
-# Remove 0s as there are few other number 0 in the response
-build_numbers=$(echo "$build_numbers" | while read -r number; do
-  echo "$number" | sed 's/^0*//'
-done)
-
-echo "Build numbers: ${build_numbers}"
-
-# Check if any build number is different from the current build number
 for number in $build_numbers; do
   if [ "$number" != "$BUILDKITE_BUILD_NUMBER" ]; then
+    duplicate_found=true
     echo "✅ Commit $BUILDKITE_COMMIT has already been built in build #$number. Skipping step..."
-    exit 1
+    buildkite-agent annotate "Commit $BUILDKITE_COMMIT has already been built in build #$number. Cancelling the build..." --style "info"
+    curl -s -H "Authorization: Bearer ${!token_var}" \
+      -X PUT "https://api.buildkite.com/v2/organizations/${BUILDKITE_ORGANIZATION_SLUG}/pipelines/${BUILDKITE_PIPELINE_SLUG}/builds/$BUILDKITE_BUILD_NUMBER/cancel"
+    rm -f "$headers" "$body"
+    exit 0
   fi
 done
 
+if [ "$duplicate_found" = false ]; then
+  echo "✅ No duplicate build found for commit $BUILDKITE_COMMIT"
+fi
+
+# Cleanup
+rm -f "$headers" "$body"
